### ISSUE TITLE
revapi-java uses internal JDK API which no longer works with JDK 9

### ISSUE THREAD

**Issue by psiroky** [revapi/revapi#69]
Hello,

I am getting the following error when trying to run the revapi-java (0.13.2) with revapi-maven-plugin (0.8.2) with `jdk-9-ea+154`:
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.8.2:report (report) on project kie-api: Execution report of goal org.revapi:revapi-maven-plugin:0.8.2:report failed: Failed to generate report.: Failed to analyze archives: Failed to obtain class tree due to compilation failure. java.lang.AssertionError: Illegal access after setAccessible(true) on a field. Wha?: class org.revapi.java.compilation.ClasspathScanner cannot access class com.sun.tools.javac.code.Symbol$ClassSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @55db2864 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.revapi:revapi-maven-plugin:0.8.2:report (report) on project kie-api: Execution report of goal org.revapi:revapi-maven-plugin:0.8.2:report failed: Failed to generate report.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:195)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:191)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1161)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution report of goal org.revapi:revapi-maven-plugin:0.8.2:report failed: Failed to generate report.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 11 more
Caused by: java.lang.IllegalStateException: Failed to generate report.
	at org.revapi.maven.ReportMojo.ensureAnalyzed(ReportMojo.java:416)
	at org.revapi.maven.ReportMojo.executeReport(ReportMojo.java:283)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 12 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to analyze archives
	at org.revapi.maven.Analyzer.analyze(Analyzer.java:418)
	at org.revapi.maven.ReportMojo.ensureAnalyzed(ReportMojo.java:411)
	... 16 more
Caused by: java.lang.IllegalStateException: Failed to obtain class tree due to compilation failure.
	at org.revapi.java.model.JavaElementForest.waitForCompilation(JavaElementForest.java:125)
	at org.revapi.java.model.JavaElementForest.getRoots(JavaElementForest.java:59)
	at org.revapi.Revapi.analyzeWith(Revapi.java:185)
	at org.revapi.Revapi.analyze(Revapi.java:126)
	at org.revapi.maven.Analyzer.analyze(Analyzer.java:416)
	... 17 more
Caused by: java.lang.RuntimeException: java.lang.AssertionError: Illegal access after setAccessible(true) on a field. Wha?
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:150)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:76)
	at org.revapi.java.compilation.ProbingAnnotationProcessor$1.call(ProbingAnnotationProcessor.java:77)
	... 4 more
Caused by: java.lang.AssertionError: Illegal access after setAccessible(true) on a field. Wha?
	at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:180)
	at org.revapi.java.compilation.Compiler.lambda$compile$75(Compiler.java:123)
	at org.revapi.java.compilation.ProbingAnnotationProcessor.process(ProbingAnnotationProcessor.java:53)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$300(JavacProcessingEnvironment.java:108)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:804)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1202)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1335)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1255)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:934)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:134)
	... 8 more
Caused by: java.lang.IllegalAccessException: class org.revapi.java.compilation.ClasspathScanner cannot access class com.sun.tools.javac.code.Symbol$ClassSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @55db2864
	at java.base/jdk.internal.reflect.Reflection.throwIllegalAccessException(Reflection.java:445)
	at java.base/jdk.internal.reflect.Reflection.throwIllegalAccessException(Reflection.java:436)
	at java.base/jdk.internal.reflect.Reflection.ensureMemberAccess(Reflection.java:112)
	at java.base/java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:407)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:399)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1065)
	at java.base/java.lang.reflect.Field.get(Field.java:406)
	at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:130)
	... 19 more
```

This is likely related to the changes in the JDK 9 which prevent accessing non-exported (internal) APIs, even after setting `setAccessible(true)`. see http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2016-October/000430.html

**Comment by metlos** [comment]
Oh, the joys 😄 There's a TODO in the code that suggests a workaround for this. I need to take a look at this and see if there isn't a Java9 specific way of achieving what I currently do by reflection..

**Comment by metlos** [comment]
This should no longer be an issue since I've figured out a way of not relying on reflection to get information I want from the compiler API.

**Comment by metlos** [comment]
I. e. this should no longer be a problem with `revapi-java-0.14.2` (which is compatible with `revapi-maven-plugin-0.9.3`).

**Comment by psiroky** [comment]
Thanks a lot @metlos! I've just tried with the versions you mentioned and all seems good (did just first round of testing, will report back in case I would find any other related issue).

**Comment by psiroky** [comment]
I am seeing a compatibility issue when running the plugin on JDK 8_152 (`revapi-java-0.14.2` + `revapi-maven-plugin-0.9.3`):
```
Caused by: java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
    at org.revapi.configuration.ReaderInputStream.<init> (ReaderInputStream.java:122)
    at org.revapi.configuration.ReaderInputStream.<init> (ReaderInputStream.java:135)
    at org.revapi.configuration.ReaderInputStream.<init> (ReaderInputStream.java:151)
    at org.revapi.configuration.JSONUtil.stripComments (JSONUtil.java:60)
    at org.revapi.maven.Analyzer.readJson (Analyzer.java:655)
    at org.revapi.maven.Analyzer.gatherConfig (Analyzer.java:538)
    at org.revapi.maven.Analyzer.analyze (Analyzer.java:434)
    at org.revapi.maven.ReportMojo.ensureAnalyzed (ReportMojo.java:425)
    at org.revapi.maven.ReportMojo.executeReport (ReportMojo.java:291)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)
```

Looks weird as the class in question was updated in 2015, so no recent changes there. I'll dig a bit more.
(The same thing works on the JDK 9.0.1).

**Comment by psiroky** [comment]
I believe I figured out a way to fix this. I opened https://github.com/revapi/revapi/issues/98 to track the issue and will create PR with the fix asap.

**Comment by psiroky** [comment]
Proposed fix: https://github.com/revapi/revapi/pull/99
